# version 3+ does different things re: networking from 2.x
# mainly things to support swarms
# aka things we don't need/want
version: '2.4'
services:
  # httpd
  glitch-web:
    image: docker.io/nginx:1.23-alpine
    container_name: glitch-web
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/var/www
    # uncomment to expose port directly
    # normally behind centeral traefik defined in production-manifests/services/traefik
    # ports:
    #   - "80:80"

    # join glitch-internal and traefik-backend networks
    # comment out the traefik lines here and in the networks: stanza below
    # if you uncomment the port exposure above
    networks:
      glitch-internal: {}
      traefik-backend: {}

  # php-fpm
  glitch-php:
    # production: track "prod" tag on ghcr.io
    # image: ghcr.io/wetfish/glitch:prod
    # for development, build the image
    # TODO: once ghcr.io autobuilds in place, change this
    build: .
    container_name: glitch-php
    restart: unless-stopped
    volumes:
      - ./public_html:/var/www
    networks:
      glitch-internal: {}

networks:
  # ephemeral, created for us by compose
  glitch-internal:
    driver: bridge
  # persistent, externally created
  traefik-backend:
    external: true
