# version 3+ does different things re: networking from 2.x
# mainly things to support swarms
# aka things we don't need/want
version: '2.4'
services:
  # httpd
  glitch-web:
    # production: track "prod-nginx" tag on ghcr.io
    image: ghcr.io/wetfish/glitch:prod-nginx
    container_name: glitch-web
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    tmpfs: /tmp
    # join glitch-internal and traefik-backend networks
    networks:
      glitch-internal: {}
      traefik-backend: {}

  # php-fpm
  glitch-php:
    # production: track "prod-php" tag on ghcr.io
    image: ghcr.io/wetfish/glitch:prod-php
    container_name: glitch-php
    restart: unless-stopped
    tmpfs: /tmp
    networks:
      glitch-internal: {}

networks:
  # ephemeral, created for us by compose
  glitch-internal:
    driver: bridge
  # persistent, externally created
  traefik-backend:
    external: true
